app = "tekkenaustriabot"
primary_region = "ams"

[build]

[http_service]
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
